version: 2
jobs:
  prepare:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
          destination: reports

  ktlint:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlint

  tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest -x lint
      - run:
          name: Run Lint Tests
          command: ./gradlew :preferenceslint:test
      - store_artifacts:
          path: build/test-results
          destination: test-results
      - store_test_results:
          path: build/test-results

  deploy:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3g
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Publish to Bintray
          command: ./gradlew build bintrayUpload -PdryRun=false

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - prepare
      - ktlint:
          requires:
            - prepare
      - tests:
          requires:
            - prepare
      - hold:
          type: approval
          requires:
            - ktlint
            - tests
          filters:
            branches:
              only:
                - master
                - /release\/.*/ # all branches starting with release/
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
                - /release\/.*/ # all branches starting with release/